name: 01-Basic Workflow Example
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  #push:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set Up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Output github context object
        run: echo "${{ toJson(github) }}"        
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: Disable workflow commands
        run: |
            echo '::warning:: This is a warning message, to demonstrate that commands are being processed.'
            stopMarker=$(uuidgen)
            echo "::stop-commands::$stopMarker"
            echo '::warning:: This will NOT be rendered as a warning, because stop-commands has been invoked.'
            echo "::$stopMarker::"
            echo '::warning:: This is a warning again, because stop-commands has been turned off.'