name: 04-schedule
on:
  #  schedule:
  #    - cron: '*/5 * * * *' 
   workflow_dispatch:  
jobs:
  Build:   
    runs-on: ubuntu-latest
    steps:
      - name: "Schedule job example"
        run: echo "Schedule job is triggered !!!"
    