name: 13-File Generation
on:
    workflow_dispatch: 
jobs:
  file_create:

    runs-on: ubuntu-latest    
    steps:
      - name: create file
        working-directory: scripts
        run: "echo hello world file >> sample.txt"
      - name: Check Dir
        run: |
          pwd
          ls
          echo ${{github.workspace}}
