name: 13-File Generation
on:
    workflow_dispatch: 
jobs:
  file_create:
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    runs-on: ubuntu-latest    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: create file
        working-directory: scripts
        run: |
          echo "hello world file" >> sample.txt
      - name: Check Dir
        run: |
          pwd
          ls
          echo ${{github.workspace}}
      # Commit and push all changed files.
      - name: GIT Commit Build Artifacts 
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
