name: Call a reusable workflow Public
on:
  workflow_dispatch:

jobs:
  job1:
    uses: rajeshraiml/github-reusable/.github/workflows/reusable-sample.yml@main
    with:
        config-path: /.github/workflows/configpath.txt
    secrets: 
        token: ${{secrets.GITHUB_TOKEN}}
  job2:
    needs: job1
    runs-on: ubuntu-latest    
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}


 