name: Container Action Workflow
on: workflow_dispatch

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container:
        image: node16
    services:      
      postgres:        
        image: postgres        
        env:
          POSTGRES_PASSWORD: postgres        
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pg
        run: npm install pg
    
      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432