name: Container Action Workflow
on: workflow_dispatch

jobs:
    container-job:
      runs-on: ubuntu-latest
      container: node:10.18-jessie
      services:
        postgres:
          image: postgres
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Install pg
          run: npm install pg
        
        - name: Install dependencies
          run: npm ci

        - name: Connect to PostgreSQL
          run: node client.js
          env:
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432