name: Request_dispatcher example
on:
    repository_dispatch:
      types: [test_result]

jobs:
  Build:   
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE