name: schedule example
on:
    schedule:
        - cron: 1 * * * *
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: "schedule 1"
            run: echo "Schedule job is triggered !!!"
    