name: schedule example
on:
    schedule:
        - cron: 1 * * * *
jobs:
    build:
        name: "Build Job"
        runs-on: ubuntu-latest
        steps:
          - name: "Step 1"
            run: echo "Schedule job is triggered !!!"
    