name: Script Execution
run-name: ${{ github.actor }} is learning GitHub Actions - Script Execution
on: 
    workflow_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./scripts
    steps:
      - name: Get code
        uses: actions/checkout@v4
       
      - name: Run script
        run: |
         pwd
         .\hello.cmd

